/** Etiquetas legibles de las columnas editables de un servicio (turno). */
export const SHIFT_FIELD_LABELS: Record<string, string> = {
  title: "Título",
  date: "Fecha",
  start_time: "Hora de inicio",
  end_time: "Hora de fin",
  slots: "Personas requeridas",
  client_id: "Cliente",
  location_id: "Ubicación",
  notes: "Notas",
  meeting_point: "Punto de encuentro",
  meeting_time: "Hora de encuentro",
  meeting_point_location_id: "Ubicación del punto de encuentro",
  job_site_location_id: "Lugar del servicio",
  job_site_address: "Dirección del servicio",
  special_instructions: "Instrucciones especiales",
  day_type: "Tipo de día",
  shift_admin_id: "Responsable",
  transportation_required: "Transporte",
  car_capacity: "Capacidad del vehículo",
  transportation_notes: "Notas de transporte",
  driver_employee_id: "Conductor",
  category_id: "Categoría",
  clock_method: "Método de fichaje",
  attendance_mode: "Modo de asistencia",
  qr_attendance_mode: "Modo QR",
  claimable: "Abierto a postulación",
};
