/**
 * lib/dispatch-writers.ts
 *
 * Side-effect layer for the read-only Core dispatch engine.
 * Consumes a `DispatchPlan` produced by `src/core/dispatch-engine.ts`
 * and applies the intended writes (assignments + broadcasts) against
 * the existing STAFly tables (`shift_assignments`, `notifications`).
 *
 * Rules:
 *  - Core never writes — only this module does.
 *  - Re-checks freshness at write time (no double-booking).
 *  - Per-action try/catch so one failure doesn't abort the whole plan.
 *  - Multi-tenant: company_id is resolved from the assignment.
 */
import { supabase } from "@/integrations/supabase/client";
import type { DispatchPlan } from "@/core/types";

export interface ApplyDispatchResult {
  assignmentId: string;
  applied: number;
  skipped: number;
  errors: Array<{ kind: string; reason: string }>;
}

/**
 * Apply a DispatchPlan generated by the core engine.
 * The ONLY place where dispatch-related writes happen.
 */
export async function applyDispatchPlan(plan: DispatchPlan): Promise<ApplyDispatchResult> {
  const result: ApplyDispatchResult = {
    assignmentId: plan.assignmentId,
    applied: 0,
    skipped: 0,
    errors: [],
  };

  // Resolve company + shift context once for all actions.
  const { data: shift } = await supabase
    .from("scheduled_shifts")
    .select("id, company_id, title, deleted_at")
    .eq("id", plan.assignmentId)
    .maybeSingle();

  if (!shift || (shift as any).deleted_at) {
    result.errors.push({ kind: "PLAN", reason: "shift_gone" });
    return result;
  }
  const companyId = (shift as any).company_id as string;
  const shiftTitle = ((shift as any).title as string) ?? "Shift";

  for (const action of plan.intendedWrites) {
    try {
      if (action.kind === "INSERT_ASSIGNMENT") {
        const r = await assignWorker({
          companyId,
          assignmentId: plan.assignmentId,
          employeeId: action.employeeId,
        });
        if (r.ok) result.applied += 1;
        else {
          result.skipped += 1;
          result.errors.push({ kind: "INSERT_ASSIGNMENT", reason: r.error ?? "unknown" });
        }
      } else if (action.kind === "BROADCAST") {
        const r = await broadcastOpportunity({
          companyId,
          assignmentId: plan.assignmentId,
          shiftTitle,
          recipientIds: await pickBroadcastAudience(companyId, action.recipientCount),
        });
        if (r.ok) result.applied += 1;
        else {
          result.skipped += 1;
          result.errors.push({ kind: "BROADCAST", reason: r.error ?? "unknown" });
        }
      }
    } catch (err: any) {
      result.errors.push({ kind: action.kind, reason: err?.message ?? String(err) });
    }
  }

  return result;
}

// ─── Writers ───────────────────────────────────────────────────────────────

async function assignWorker(args: {
  companyId: string;
  assignmentId: string;
  employeeId: string;
}): Promise<{ ok: boolean; error?: string }> {
  // Guard: don't double-book the same worker on this shift.
  const { data: existing } = await supabase
    .from("shift_assignments")
    .select("id")
    .eq("shift_id", args.assignmentId)
    .eq("employee_id", args.employeeId)
    .not("status", "in", '("rejected","removed")')
    .maybeSingle();
  if (existing) return { ok: false, error: "already_assigned" };

  const { error } = await supabase.from("shift_assignments").insert({
    shift_id: args.assignmentId,
    employee_id: args.employeeId,
    company_id: args.companyId,
    status: "confirmed",
    assignment_role: "worker",
  } as any);
  if (error) return { ok: false, error: error.message };
  return { ok: true };
}

async function broadcastOpportunity(args: {
  companyId: string;
  assignmentId: string;
  shiftTitle: string;
  recipientIds: string[];
}): Promise<{ ok: boolean; error?: string; sent: number }> {
  if (!args.recipientIds.length) return { ok: false, error: "no_audience", sent: 0 };

  const rows = args.recipientIds.map(empId => ({
    company_id: args.companyId,
    recipient_id: empId,
    recipient_type: "employee",
    type: "shift_urgent",
    title: "🚨 Turno por cubrir",
    body: `Necesitamos cubrir "${args.shiftTitle}". ¿Estás disponible?`,
    metadata: { shift_id: args.assignmentId, source: "core_dispatch" } as any,
    created_by: null,
  }));

  const { error } = await supabase.from("notifications").insert(rows as any);
  if (error) return { ok: false, error: error.message, sent: 0 };
  return { ok: true, sent: rows.length };
}

/**
 * Pick the broadcast audience: active employees in the company, capped.
 * Kept dumb on purpose — the smart targeting belongs in core's candidate
 * sourcing, not in the writer.
 */
async function pickBroadcastAudience(companyId: string, cap: number): Promise<string[]> {
  const { data } = await supabase
    .from("employees")
    .select("id")
    .eq("company_id", companyId)
    .eq("is_active", true)
    .limit(Math.max(1, Math.min(cap || 20, 50)));
  return ((data ?? []) as Array<{ id: string }>).map(e => e.id);
}
