// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Useful to verify connectivity to the Stafly MCP server.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var whoami_default = defineTool2({
  name: "whoami",
  title: "Who am I",
  description: "Return the identity of the signed-in Stafly user connected via MCP (user id, email, client id).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      client_id: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-my-shifts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_shifts_default = defineTool3({
  name: "list_my_shifts",
  title: "List my upcoming shifts",
  description: "List the signed-in worker's upcoming shift assignments (next N days). Respects Stafly RLS \u2014 only shifts the caller is allowed to see are returned.",
  inputSchema: {
    days_ahead: z2.number().int().min(1).max(30).default(7).describe("How many days ahead to look."),
    limit: z2.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days_ahead, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const from = /* @__PURE__ */ new Date();
    const to = new Date(Date.now() + days_ahead * 24 * 60 * 60 * 1e3);
    const { data, error } = await supabase.from("shift_assignments").select(
      "id, status, scheduled_shifts!inner(id, start_at, end_at, title, meeting_point, publication_status)"
    ).gte("scheduled_shifts.start_at", from.toISOString()).lte("scheduled_shifts.start_at", to.toISOString()).order("scheduled_shifts(start_at)", { ascending: true }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { assignments: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jplhtputzixwqarqlrth";
var mcp_default = defineMcp({
  name: "stafly-mcp",
  title: "Stafly",
  version: "0.1.0",
  instructions: "Stafly agent integration. Read-only tools for identity and worker shifts. Use `echo` to verify connectivity, `whoami` to confirm the signed-in Stafly user, and `list_my_shifts` to view upcoming assignments. Payroll, time entries, employees, and shifts writes are intentionally not exposed.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [echo_default, whoami_default, list_my_shifts_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
