import { useState, useEffect, useMemo } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { useCompany } from "@/hooks/useCompany";
import { usePageView } from "@/hooks/useAuditLog";
import { PageHeader } from "@/components/ui/page-header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { toast } from "sonner";
import { format } from "date-fns";
import { es } from "date-fns/locale";
import { cn } from "@/lib/utils";
import { formatDisplayText } from "@/lib/format-helpers";
import AuditPanel from "@/components/audit/AuditPanel";
import {
  Receipt, Plus, Loader2, Search, MoreHorizontal, Send, Eye,
  CheckCircle2, XCircle, DollarSign, FileText, Download, Printer,
} from "lucide-react";

const STATUS_CFG: Record<string, { label: string; color: string }> = {
  draft: { label: "Borrador", color: "bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-400" },
  approved: { label: "Aprobada", color: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400" },
  issued: { label: "Emitida", color: "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400" },
  sent: { label: "Enviada", color: "bg-violet-100 text-violet-700 dark:bg-violet-900/30 dark:text-violet-400" },
  viewed: { label: "Vista", color: "bg-sky-100 text-sky-700 dark:bg-sky-900/30 dark:text-sky-400" },
  partially_paid: { label: "Pago parcial", color: "bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400" },
  paid: { label: "Pagada", color: "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400" },
  overdue: { label: "Vencida", color: "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400" },
  voided: { label: "Anulada", color: "bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400" },
};

interface Invoice {
  id: string;
  invoice_number: string;
  client_id: string;
  issue_date: string;
  due_date: string | null;
  subtotal: number;
  tax_amount: number;
  discount_amount: number;
  grand_total: number;
  status: string;
  created_at: string;
}

export default function Invoices() {
  usePageView("Facturación");
  const { user } = useAuth();
  const { selectedCompanyId } = useCompany();

  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [clients, setClients] = useState<{ id: string; name: string }[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [createOpen, setCreateOpen] = useState(false);
  const [saving, setSaving] = useState(false);

  const [form, setForm] = useState({ client_id: "", due_date: "", external_notes: "", internal_notes: "" });

  const loadData = async () => {
    if (!selectedCompanyId) return;
    setLoading(true);
    const [invRes, cliRes] = await Promise.all([
      supabase.from("invoices").select("*").eq("company_id", selectedCompanyId).order("created_at", { ascending: false }),
      supabase.from("clients").select("id, name").eq("company_id", selectedCompanyId).is("deleted_at", null),
    ]);
    setInvoices((invRes.data ?? []) as Invoice[]);
    setClients(cliRes.data ?? []);
    setLoading(false);
  };

  useEffect(() => { loadData(); }, [selectedCompanyId]);

  const filtered = useMemo(() => {
    let r = invoices;
    if (search) {
      const q = search.toLowerCase();
      r = r.filter(inv => inv.invoice_number.toLowerCase().includes(q));
    }
    if (statusFilter !== "all") r = r.filter(inv => inv.status === statusFilter);
    return r;
  }, [invoices, search, statusFilter]);

  const handleCreate = async () => {
    if (!form.client_id || !selectedCompanyId) { toast.error("Selecciona un cliente"); return; }
    setSaving(true);
    const { error } = await supabase.from("invoices").insert({
      company_id: selectedCompanyId,
      client_id: form.client_id,
      invoice_number: "", // auto-generated by trigger
      due_date: form.due_date || null,
      external_notes: form.external_notes.trim() || null,
      internal_notes: form.internal_notes.trim() || null,
      created_by: user?.id,
    } as any);
    if (error) { toast.error(error.message); setSaving(false); return; }
    toast.success("Factura creada");
    setSaving(false); setCreateOpen(false);
    setForm({ client_id: "", due_date: "", external_notes: "", internal_notes: "" });
    loadData();
  };

  const handleStatusChange = async (id: string, newStatus: string) => {
    const updates: any = { status: newStatus };
    if (newStatus === "sent") updates.sent_at = new Date().toISOString();
    if (newStatus === "paid") updates.paid_at = new Date().toISOString();
    if (newStatus === "approved") { updates.approved_by = user?.id; updates.approved_at = new Date().toISOString(); }
    if (newStatus === "voided") { updates.voided_by = user?.id; updates.voided_at = new Date().toISOString(); }
    const { error } = await supabase.from("invoices").update(updates).eq("id", id);
    if (error) { toast.error(error.message); return; }
    toast.success(`Estado actualizado`);
    loadData();
  };

  const getClientName = (id: string) => clients.find(c => c.id === id)?.name || "—";

  const totals = useMemo(() => {
    const unpaid = invoices.filter(i => ["issued","sent","viewed","overdue"].includes(i.status)).reduce((s, i) => s + (i.grand_total || 0), 0);
    const paid = invoices.filter(i => i.status === "paid").reduce((s, i) => s + (i.grand_total || 0), 0);
    const overdue = invoices.filter(i => i.status === "overdue").reduce((s, i) => s + (i.grand_total || 0), 0);
    return { unpaid, paid, overdue };
  }, [invoices]);

  return (
    <div className="space-y-5">
      <PageHeader
        variant="1"
        icon={Receipt}
        title="Facturación"
        subtitle="Gestiona facturas y cuentas por cobrar"
        rightSlot={
          <Dialog open={createOpen} onOpenChange={setCreateOpen}>
            <DialogTrigger asChild>
              <Button size="sm" className="h-8 text-xs gap-1.5"><Plus className="h-3.5 w-3.5" /> Nueva factura</Button>
            </DialogTrigger>
            <DialogContent className="max-w-md">
              <DialogHeader><DialogTitle>Nueva factura</DialogTitle></DialogHeader>
              <div className="space-y-4 pt-2">
                <div>
                  <Label className="text-xs">Cliente *</Label>
                  <Select value={form.client_id || "none"} onValueChange={v => setForm(f => ({ ...f, client_id: v === "none" ? "" : v }))}>
                    <SelectTrigger className="h-9 text-sm mt-1"><SelectValue placeholder="Seleccionar cliente" /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="none">Seleccionar...</SelectItem>
                      {clients.map(c => <SelectItem key={c.id} value={c.id}>{formatDisplayText(c.name, "name")}</SelectItem>)}
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label className="text-xs">Fecha de vencimiento</Label>
                  <Input type="date" value={form.due_date} onChange={e => setForm(f => ({ ...f, due_date: e.target.value }))} className="h-9 text-sm mt-1" />
                </div>
                <div><Label className="text-xs">Notas externas</Label><Textarea value={form.external_notes} onChange={e => setForm(f => ({ ...f, external_notes: e.target.value }))} rows={2} className="text-sm mt-1" placeholder="Visible en la factura..." /></div>
                <div><Label className="text-xs">Notas internas</Label><Textarea value={form.internal_notes} onChange={e => setForm(f => ({ ...f, internal_notes: e.target.value }))} rows={2} className="text-sm mt-1" placeholder="Solo admins..." /></div>
                <Button onClick={handleCreate} disabled={saving} className="w-full h-10 text-sm">
                  {saving ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : null}
                  Crear factura
                </Button>
              </div>
            </DialogContent>
          </Dialog>
        }
      />

      {/* KPIs */}
      <div className="grid grid-cols-3 gap-3">
        <div className="rounded-xl border border-border/20 p-4 bg-card">
          <p className="text-[10px] text-muted-foreground font-medium">Cuentas por cobrar</p>
          <p className="text-xl font-bold text-foreground">${totals.unpaid.toLocaleString("en-US", { minimumFractionDigits: 2 })}</p>
        </div>
        <div className="rounded-xl border border-border/20 p-4 bg-card">
          <p className="text-[10px] text-muted-foreground font-medium">Cobrado</p>
          <p className="text-xl font-bold text-emerald-600">${totals.paid.toLocaleString("en-US", { minimumFractionDigits: 2 })}</p>
        </div>
        <div className="rounded-xl border border-border/20 p-4 bg-card">
          <p className="text-[10px] text-muted-foreground font-medium">Vencido</p>
          <p className="text-xl font-bold text-red-600">${totals.overdue.toLocaleString("en-US", { minimumFractionDigits: 2 })}</p>
        </div>
      </div>

      {/* Search */}
      <div className="flex gap-2">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground" />
          <Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar por número de factura..." className="pl-9 h-9 text-sm" />
        </div>
        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="h-9 w-40 text-sm"><SelectValue placeholder="Estado" /></SelectTrigger>
          <SelectContent>
            <SelectItem value="all">Todos</SelectItem>
            {Object.entries(STATUS_CFG).map(([k, v]) => <SelectItem key={k} value={k}>{v.label}</SelectItem>)}
          </SelectContent>
        </Select>
      </div>

      {/* Table */}
      {loading ? (
        <div className="flex items-center justify-center py-20"><Loader2 className="h-6 w-6 animate-spin text-muted-foreground" /></div>
      ) : filtered.length === 0 ? (
        <div className="text-center py-16">
          <Receipt className="h-10 w-10 text-muted-foreground/30 mx-auto mb-3" />
          <p className="text-sm text-muted-foreground">No hay facturas</p>
          <Button variant="outline" size="sm" className="mt-3" onClick={() => setCreateOpen(true)}><Plus className="h-3.5 w-3.5 mr-1" /> Crear primera factura</Button>
        </div>
      ) : (
        <div className="rounded-xl border border-border/20 overflow-hidden bg-card">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border/15 bg-muted/30">
                  <th className="text-left px-4 py-2.5 text-[11px] font-semibold text-muted-foreground">Factura</th>
                  <th className="text-left px-3 py-2.5 text-[11px] font-semibold text-muted-foreground">Cliente</th>
                  <th className="text-left px-3 py-2.5 text-[11px] font-semibold text-muted-foreground">Emisión</th>
                  <th className="text-left px-3 py-2.5 text-[11px] font-semibold text-muted-foreground">Vencimiento</th>
                  <th className="text-right px-3 py-2.5 text-[11px] font-semibold text-muted-foreground">Total</th>
                  <th className="text-left px-3 py-2.5 text-[11px] font-semibold text-muted-foreground">Estado</th>
                  <th className="w-10"></th>
                </tr>
              </thead>
              <tbody>
                {filtered.map(inv => {
                  const st = STATUS_CFG[inv.status] || { label: inv.status, color: "bg-muted text-muted-foreground" };
                  return (
                    <tr key={inv.id} className="border-b border-border/10 hover:bg-muted/20 transition-colors">
                      <td className="px-4 py-3 font-mono text-sm font-semibold">{inv.invoice_number}</td>
                      <td className="px-3 py-3 text-xs">{formatDisplayText(getClientName(inv.client_id), "name")}</td>
                      <td className="px-3 py-3 text-xs">{format(new Date(inv.issue_date), "dd MMM yy", { locale: es })}</td>
                      <td className="px-3 py-3 text-xs">{inv.due_date ? format(new Date(inv.due_date), "dd MMM yy", { locale: es }) : "—"}</td>
                      <td className="px-3 py-3 text-right font-semibold">${inv.grand_total.toLocaleString("en-US", { minimumFractionDigits: 2 })}</td>
                      <td className="px-3 py-3"><Badge variant="secondary" className={cn("text-[10px] font-semibold", st.color)}>{st.label}</Badge></td>
                      <td className="px-2 py-3">
                        <DropdownMenu>
                          <DropdownMenuTrigger asChild><Button variant="ghost" size="icon" className="h-7 w-7"><MoreHorizontal className="h-3.5 w-3.5" /></Button></DropdownMenuTrigger>
                          <DropdownMenuContent align="end">
                            {inv.status === "draft" && <DropdownMenuItem onClick={() => handleStatusChange(inv.id, "approved")}><CheckCircle2 className="h-4 w-4 mr-2" /> Aprobar</DropdownMenuItem>}
                            {inv.status === "approved" && <DropdownMenuItem onClick={() => handleStatusChange(inv.id, "issued")}><FileText className="h-4 w-4 mr-2" /> Emitir</DropdownMenuItem>}
                            {["issued","viewed"].includes(inv.status) && <DropdownMenuItem onClick={() => handleStatusChange(inv.id, "sent")}><Send className="h-4 w-4 mr-2" /> Marcar enviada</DropdownMenuItem>}
                            {["sent","viewed","overdue"].includes(inv.status) && <DropdownMenuItem onClick={() => handleStatusChange(inv.id, "paid")}><DollarSign className="h-4 w-4 mr-2" /> Marcar pagada</DropdownMenuItem>}
                            {!["paid","voided"].includes(inv.status) && <DropdownMenuItem onClick={() => handleStatusChange(inv.id, "voided")} className="text-destructive"><XCircle className="h-4 w-4 mr-2" /> Anular</DropdownMenuItem>}
                          </DropdownMenuContent>
                        </DropdownMenu>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}

      <AuditPanel entityType="invoice" />
    </div>
  );
}
